
import { GoogleGenAI } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable is not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export async function generateWallpapers(prompt: string): Promise<string[]> {
  try {
    // Enhance prompt for better wallpaper generation
    const enhancedPrompt = `${prompt}, phone wallpaper, vertical, 9:16 aspect ratio, high detail, cinematic`;
    
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001',
        prompt: enhancedPrompt,
        config: {
          numberOfImages: 4,
          aspectRatio: '9:16',
          outputMimeType: 'image/jpeg',
        },
    });

    if (!response.generatedImages || response.generatedImages.length === 0) {
      throw new Error("No images were generated by the API.");
    }

    const imageUrls = response.generatedImages.map(img => {
        const base64ImageBytes: string = img.image.imageBytes;
        return `data:image/jpeg;base64,${base64ImageBytes}`;
    });

    return imageUrls;
  } catch (error) {
    console.error("Error generating wallpapers with Gemini:", error);
    throw new Error("Failed to generate wallpapers.");
  }
}
